from .agnn import AGNN
from .gat import GAT
from .gcn import GCN
from .gin import GIN
from .set2set import Set2SetNet
from .sgcn import SGCN
from .tag import TAG
from .tag_jk import TAGWithJK
from  .tag_jk_learn import TAGWithJKLearn
from .tag_learn import TAGLearn
from .gcn_learn import GCNLearn
from .sgcn_learn import SGCNLearn
from .eegnet import EEGNet
from .tag_sort_pool_ import TAGSortPool
